### ISSUE TITLE
Mytown + TConstruct crash using Lumber Axe

### ISSUE THREAD

**Issue by Esctogrillo** [CyberdyneCC/Thermos#358]
**Crash report** https://gist.github.com/Esctogrillo/c33e53d66b359f9c769b8ccc5be558ff

**Explanation of issue:**Crash when using lumber axe near to a town (MyTown protection mod)

**How to recreate this issue:**Cut a tree with lumber axe near to a town

**Modpack Name:** [JordannPack] (https://github.com/TheKingdomServer/JordannPack)

**Mods Installed:**JordannPack github ^

**Thermos Version:**54

**Forge Version:**1614

I should post this crash on MyTown github, but the devs doesn't answer.

**Comment by Time6628** [comment]
Non-Thermos issue.

**Comment by Robotia** [comment]
It seems to be that the Tinkers Construct mod gets stuck in an infinite loop while trying to remove a tree block. :confused: 
Because the blocks are not broken (they are protected), the item keeps trying to break the tree blocks. I would suggest contacting the Tinkers Construct developers about this.
