### ISSUE TITLE
Magical Crops - lost items on Death.

### ISSUE THREAD

**Issue by BlayzerQ** [CyberdyneCC/Thermos#397]
If during the fall in zivicio armor of Magical Crops and unequipe one armor item and keep it in a mouse, not laying in inventory, after the death of all things fall in the inventory will be lost, along with the armor.
No Errors on log.

Thermos:1.7.10-1614.57
magicalcrops{4.0.0_PUBLIC_BETA_3}

**Comment by Tencao** [comment]
I can also confirm this happens on my modpack running Thermos

**Comment by iKaneki-Ken** [comment]
Follow the template regardless to whether you think it's relevant or not. This includes providing server logs as well as mods and plugins used while the server is running.

**Comment by Tencao** [comment]
You know, having this kind of attitude is exactly what's driving people away from thermos, myself included.

**Comment by spannerman79** [comment]
_First and foremost I am not a developer of Thermos - you don't see a badge next to my name thus this is my own personal point of view_

----

> You know, having this kind of attitude is exactly what's driving people away from thermos, myself included.

@Tencao when you submit an issue with **any** issue tracker if they have a template system in place then it is **expected** that you fill out such template.  The template is there for a reason - to obtain the information required without needing countless comments after the fact requesting said information.

Opening an issue automatically binds you to agree to any stipulations that the dev, devs or dev team requires.  And if you think that is harsh I can tell you now that you won't even find any sort of collaboration work - be it personal or professional on any sort of level.

Even when you click on "New Issue" the first line at the top is `Please review the guidelines for contributing to this repository.`.  Submitting an issue binds you to whatever contribution guidelines that repository requires. In fact this is standard for the majority of repositories that are not just on GitHub but self hosted with GitLab.

There is a phrase for the above - Git Etiquette. Learn it, love it, embrace it.

**Comment by iKaneki-Ken** [comment]
@Tencao Yeah, cause there's really a large selection of Modded Minecraft server software for MC1.7.10. /s

If you don't like the rules of this Github repository, don't submit issues. It's that simple.

**Comment by Tencao** [comment]
Sorry to tell you, but I'm part of several mod projects and modpacks already, so I'm very well aware how the typical issue response is, but in this case, the issue was described perfect. With this, and this, this happens, you cant get more simple and to the point than that, but because no logs was provided, which alot of the time with thermos, no logs are produced, you cant exactly rely or expect people to upload something which isn't outputting any relevant information.  Sponge for example would happily look into this issue and request further information when needed, but instead of you trying to look into this with the information already provided, you're instead outright dismissing the issue, and also preventing Thermos from growing.

**Comment by iKaneki-Ken** [comment]
Really? No logs produced? I replicated this issue with Thermos debugging options enabled and spotted after some time of looking through the entries it posted in the *log* file.

All in all, ignorance of not knowing how to enable, let alone use the debugging features isn't the problem of the devs of Thermos. I suggest you sit down and actually learn how to properly use Thermos before claiming things like "There were no logs produced". There were no logs produced because like I said a couple of lines above, neither you or the person that submitted this ticket turned on the debugging options.

Time never outright dismissed it, he closed the ticket because the issue creator didn't follow the provided template, not only that, he provided absolutely no information other than "I did this and this happened".

So again, follow the rules that a Github repository sets out for the users that visit it and get help. Or don't and don't get help. It's that simple.

**Comment by spannerman79** [comment]
> but in this case, the issue was described perfect. With this, and this, this happens, you cant get more simple and to the point than that, but because no logs was provided, which alot of the time with thermos, no logs are produced, you cant exactly rely or expect people to upload something which isn't outputting any relevant information

Wrong - I can take a rough 5 second guess at 6 different things that could cause this. Without the template being filled as requested no help can be given to pin point issues.

> Sponge for example would happily look into this issue and request further information when needed, but instead of you trying to look into this with the information already provided, you're instead outright dismiss the issue

Being told this is like how some of my friends use to call me and say "Oh windows just crashed". I asked for more details and the response was "Oh i did nothing" When I took a look at their system it was (~70% of the time) riddled with junkware from someone looking at porn on that computer.

**Comment by Tencao** [comment]
> Really? No logs produced? I replicated this issue with Thermos debugging options enabled and spotted after some time of looking through the entries it posted in the log file.

So you're saying that was able to confirm this bug, yet still dismissed it anyway, I think that further proves my point

> Being told this is like how some of my friends use to call me and say "Oh windows just crashed". I asked for more details and the response was "Oh i did nothing" When I took a look at their system it was (~70% of the time) riddled with junkware from someone looking at porn on that computer.

The difference is, no one asked for additional information here. If you responded with "turn on debug mode, copy the output to pastebin and link it back here", I'm sure he or someone else would have gladly, but instead the issue was dismissed without ever looking into it properly, which considering @iKaneki-Ken confirmed the issue, goes to show how many legit issues are probably being completely ignored because simple questions and taking the time to look into issues isn't happening.

**Comment by iKaneki-Ken** [comment]
No, I'm not dismissing it, I'm actually working on fixing it myself right now. My point to is, if you're too lazy to follow the rules of a github repository and fill out a given template properly, just because the dev closes the ticket doesn't mean he's dismissing your issue, It means he's not going to waste his time.

**Comment by MrTakedi** [comment]
Closing the ticket is dismissing the issue.

Kthnxbai.

**Comment by Robotia** [comment]
The issue was marked as `invalid` because OP ignored the template that is shown when one creates an issue and instead chose to delete it.
