### ISSUE TITLE
Translate russian to english

### ISSUE THREAD

**Issue by Paktosan** [CyberdyneCC/Thermos#404]
Can you please translate all russian stuff to english? This would improve readability.

**Comment by Time6628** [comment]
https://translate.google.com

**Comment by Paktosan** [comment]
Let me copy something from somewhere else:
Yes, but often Google Translate is not that great so there might be misunderstandings.
Also it is not good style to mix languages.

**Comment by Robotia** [comment]
If you are looking through the commits, then please try to contribute. This time we have spent on Thermos, it comes from our free time. Don't just take parts you like and claim it as your own, or release derivatives without sharing the source publicly: that breaks the GPL license of this project.

If you don't understand Java, there's not much reason to be reading them.

If you know Java and are willing to contribute, I suggest you do so rather than ask for translations of commit messages...

Thank you,

Robotia
