### ISSUE TITLE
help to scared to start up server again it took down the whole vps

### ISSUE THREAD

**Issue by webbster64** [CyberdyneCC/Thermos#427]
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*

**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*

**Explanation of issue:**

**How to recreate this issue:**

**Modpack Name:** *(Only if public)*

**Mods Installed:**

**Plugins Installed:**

**Warmroast Report:** *(Optional)*

**Thermos Version:**

**Forge Version:**
https://drive.google.com/open?id=0By58KMiVWZkVWHlIWmNXWTVyNms

**Comment by Yanniclord** [comment]
Beside the forge version, you provided nothing, no info or alike. Also, the title is very confusing without commas, it should be "Help, too scared to start up my server again, it took down the whole VPS"

**Comment by webbster64** [comment]
nvm it was the vanilla doing it 
not the modded

**Comment by Yanniclord** [comment]
Uhm, ok, so issue closed then. Can you close it?

**Comment by Robotia** [comment]
Closing this issue as it seems to be resolved...

In the future, please actually use the template instead of quickly hitting submit.

We will not help you if you submit issues like this, it's basically spam.

I get an email for every issue that is submitted and reading issues like this make me question that decision.

**Comment by webbster64** [comment]
im really sorry someone forgot to tell me that the vanilla server took most of the ram its off now and my server is running perfectly
