### ISSUE TITLE
Players get DC for one time, then they can re-log and all seems fine ?

### ISSUE THREAD

**Issue by lightning02** [CyberdyneCC/Thermos#448]
As the title, before there was this issue of random dc, actually seems that the dc happen when people try to log in, then, after dc, if people try to re-log all goes fine...
I tryed to post this problem on Reika, since draonAPI is blamed by the logs, but they say that Thermos, bukkit etz are no longer supported.. again?!  :(
Why modders hate you so much? :/
By the way, is there something that can be done on your side?
If I let the world runs on a normal Forge server players get logged in on first try in effect...
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1041

**Comment by spannerman79** [comment]
If you wish to use DragonAPI (and other mods that need it) you will need to use vanilla forge. That is the "cost" involved with wanting DragonAPI etc.

**Comment by Time6628** [comment]
Non-Thermos issue.

**Comment by lightning02** [comment]
I sadly agree with spanneman... 
but Time, how can be a non-thermos issue if on forge server this problem doesn't occur?
I mean, is still an "incompatibility" or something, isn't it? :l

**Comment by Time6628** [comment]
> I sadly agree with spanneman... 
but Time, how can this be a non-thermos issue if on forge server this problem doesn't occur?
I mean, is still an "incompatibility" or something, isn't it? :l

It's not a Thermos issue because all it needs is a null check. Due to the way Cauldron/Thermos handles players, sometimes the players return null, which most times causes mods to throw errors when they try to send a packet to the player. Since Thermos is not supported by DragonAPI, you will have to make a fix for it yourself.

**Comment by lightning02** [comment]
any suggestion to make a null-check for dragon api packets? I'm not really skilled to be honest :C

**Comment by spannerman79** [comment]
> Since Thermos is not supported by DragonAPI, you will have to make a fix for it yourself.

> any suggestion to make a null-check for dragon api packets? I'm not really skilled to be honest :C

**No**.  Do not do either of this.  The reason why is because usage of DragonAPI (and other mods that depend on it) requires you to follow [these](https://sites.google.com/site/reikasminecraft/modifications) rules.  In specific to the following quote;

> Also, if you are playing singleplayer, you can make whatever kind of changes you like, as long as noone but you is playing that version. **You are even permitted to make custom builds of the code, so long as you never share it.** The only caveat is that such modified versions are ineligible for tech support.

I made bold within that quote of what needs to be understood.  As it will be a server and multiplayer more then likley you'll need to distribute that changed jar. Thus you'll need to follow [these](https://sites.google.com/site/reikasminecraft/pack-permissions-and-rules) rules also.  In specific to number 6 under modpack rules.

Doing the beforehand meantioned will revoke your modpack permission if you have your modpack on Technic etc.

**Comment by Time6628** [comment]
You do not have to distribute the changed jar, just check if the player is null on the server.
