### ISSUE TITLE
RTG Generation is broken on Thermos

### ISSUE THREAD

**Issue by NoireDvachevsky** [CyberdyneCC/Thermos#486]
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
http://pastebin.com/jk5Fs8zr

**Explanation of issue:**
World generation made by RTG seems broken on thermos. Chunks are generating without any trees or decorations, no villages too. Streams mod has broken too, cobblestone rivers everywhere.

**How to recreate this issue:**
Start a world with RTG + climate control generation.

**Mods Installed:**
Realistic Terrain Gen
Climate Control
Streams mod

**Thermos Version:**
1614.56

**Comment by YuRaNnNzZZ** [comment]
Can confirm - server kicking someone with [this error](http://pastebin.com/pr0PJUEQ) before generating new chunks without decorations.

**Comment by enterprise12nx** [comment]
i have both these mods and i have made multiple public server worlds and loaded them out using worldborder to 15kx15k blocks without problem

**Comment by Harjas2102** [comment]
Going to take a educated guess and say that this is an External Issue @Time6628

**Comment by Robotia** [comment]
Fixed in Build 58.

**Comment by NoireMann** [comment]
@enterprise12nx can you say, which build you used to generate map?

**Comment by NoireMann** [comment]
World generation and chunk populating partly fixed in b909f0a981037fc90eccce0336c055791441ce76 , but there are lots of generation problems still.

Lots of single unpopulated (bald) chunks without trees and decorations, weird tree and other things generation (trees are cut near the chunk borders)

Streams` rivers are generating, water is placed but cobblestone still spawns above the generated water.

**Comment by NoireDvachevsky** [comment]
Maybe it is possible to tweak RTG, or maybe make an exclusion for RTG-world-generator to generate chunks force-forgelike? 
I mean, force forgelike in world generation algorithms. Because, while i am using RTG, no one plugin like WorldEdit works correct with chunk-related things. For example, chunk regeneration made by WorldEdit makes chunk bald and unpopulated.

**Comment by Robotia** [comment]
@NoireDvachevsky si vous êtes français (je pense que ça est le cas parce que vous avez "noire" dans votre nomme d'utilisateur), je peux parler dans français au lieu de l'anglais. Pourquoi avez-vous besoin d'utiliser ce mod? Il pourrait y avoir un autre mod aussi utile (qui fonctionne bien)?

If you are French (I think that is the case because you have "noire" in your username), I can speak in French instead of English. Why do you need to use this mod? Could there be another mod that is as useful as this one (which works well)?

**Comment by NoireDvachevsky** [comment]
No, I am russian. You may remember me as Hitagifag at Discord, I am trying to reach you there, but you are offline :C

What about this mod - I have found a nice seed for generating an earthlike world, and I have promised to the players of my server, that this world will be available for playing at September.

In fact, the parent mod of RTG - RWG (Realistic world generation) is working well with Thermos. But it has less features and fixes than the RTG mod.

**Comment by Robotia** [comment]
I am not active on Discord anymore, sorry about that.

This mod is difficult to support if it is causing so many problems :confused:

**Comment by spannerman79** [comment]
The RTG team have outright refused to support Cauldron etc https://github.com/Team-RTG/Realistic-Terrain-Generation/issues/832#issuecomment-232791000

**Comment by NoireDvachevsky** [comment]
So, this means no support for my issue?

**Comment by spannerman79** [comment]
I cannot speak for the Thermos dev team directly - I am not a member (no badge next to my name) but from my experience if a dev, devs or dev group have stated that they don't and won't support Cauldron and/or its forks then more then likley you won't get any support.

Either use Vanilla forge if you **must** need RTG or use some other generator that is known to have no issues (BOP example)

**Comment by NoireDvachevsky** [comment]
But we are talking about tweaking thermos to be compatible with RTG, but not vice versa. I am 100% sure, that this problem solution could be made in a couple of code strings.

Okay, i might not be excellent programmer, but this trick worked with Forge/Bukkit events. They are working well, but why not to force forge-generate the world while RTG generator is enabled?

If this absolutely impossible, I am sorry to trouble all the Thermos and RTG dev teams.

**Comment by NoireDvachevsky** [comment]
OMG. Just tested my pack WITHOUT Streams, but with RTG/CC. Everything is okay, WorldEdit regeneration work fine... But when I am adding streams + farseek = bugs and bald chunks.

@Robotia , please, close this ticket. I will open a new issue for Streams with detailed report.

I am very sorry for being such an annoying person. :(

**Comment by enterprise12nx** [comment]
@NoireDvachevsky use my modpack Industrial Age The Turning i have both those mods and i havent noticed any problems, perhaps i am using different versions of the mods

**Comment by NoireDvachevsky** [comment]
@enterprise12nx so you have pregenned a world on Thermos with these mods?

Could you please make a list of mods and versions that you are using? Including Thermos build

**Comment by Sunconure11** [comment]
This issue is sporadic for me, someone connected one possible culprit of this random corruption to Magia Naturalis when I asked about it in the past. My modpack Compitum Magia has it sporadically. You are obviously using more mods than you are letting off. I suggest posting a full mod list. Also, look through my mod list, and see if you have any other matching mods aside from the obvious (Climate Control, RTG, Streams)

**Comment by enterprise12nx** [comment]
@NoireDvachevsky Yes using worldborder i generated out to 15kx15k chunks
The full mod list verified by FTB:
Using Thermos Build 57 on a Dedicated Public Server

AdditionalPipes by tcooc
Advanced Machines Immibis by Immibis - Granted
Advanced Repulsion Systems by Immibis - Granted
Advanced Solar Panels by SeNtiMeL
AE2 Stuff by bdew
AgriCraft by InfinityRaider
Animals+ by Click_Me
AOBD 2 by ganymedes01
Applied Energistics by AlgorithmX2
Baubles by Azanor
Bdlib by bdew
BiblioCraft by Nuchaz
Big Reactors by Erogenous Beef
Binnie Patcher by Chocohead - Granted
Binnie's Mods by Binnie
Biomes O' Plenty by TDWP_FTW, Adubbz
Brandon's Core by brandon3055
bspkrsCore by bspkrs
Buildcraft by CovertJaguar, SirSengir, Krapht, cpw, spacetoad, asiekierka
Carpenter's Blocks by Mineshopper
ChickenChunks by Chickenbones
Chisel 2 by warlordjones, tterrag1098, TheCricket26, Drullkus
Chocolate Quest by Chocolatin
Climate Control by Zeno410 0.5Beta50
CodeChickenCore by Chickenbones
CodeChickenLib by Chickenbones
CoFH Core by CoFH team
ComputerCraft by Dan200
CookieCore by ephys
CoroUtil by Corosauce
Dark Core by ShaneDarkholme
Default World Generator by fireball1725
Dimensional Anchors by immibis
EJML-Core by IC2 Dev Team - Granted
Electrical Age by Dolu1990
Enchanting Plus by Freyjadono, mssodin23, GnRSlash, Qizzok, xkyouchoux
Ender Tech by Drayshak
EnderCore by tterrag
EnderIO by CrazyPants
EnderStorage by Chickenbones
Extra Cells by Leonelf
ExtraTiC by Glassmaker
Farseek by delvr
FastCraft by Player - Granted
Flaxbeard's Steam Power by The Esteemed Innovation Team
Forbidden Magic by SpitefulFox
Forestry by SirSengir
Forge Multipart by Chickenbones
Forge Relocation - FMP Plugin by MrTJP
ForgeRelocation by MrTJP
Gadomancy by makeo, HellFirePvP - Granted
Galacticraft by Micdoodle8
Gendustry by bdew
Gravitation Suite by SeNtiMeL
Growthcraft by Gwafu
Hardcore Ender Expansion by chylex - Granted
HarvestCraft by MatrexsVigil, Rhodox
Hat Stand by iChun
Hats by iChun
Highlands by sdj64
iChunUtil by iChun
Immersive Engineering by BluSunrize
Immersive Integration by Unwritten Fun
Immibis Core by immibis
Immibis's Microblocks by immibis
In-Game Wiki Mod by MineMaarten
IndustrialCraft 2 by IC2 Dev Team
Inventory Tweaks by Kobata
IronChests by cpw, progwml6
JABBA by ProfMobius
Liquid XP by immibis
Localized Weather & Stormfronts by Corosauce
LogisticsPipes by davboecki, theZorro266, GUIpsp, AartBluestoke, ArtForz
Magic Bees by MysteriousAges
Malisis Core by Ordinastie
Malisis Doors by Ordinastie
Mantle by mDiyo, progwml6
Matmos by Hurricaaane
Matter Overdrive by simeonradivoev
McJtyLib by McJty
Mekanism by aidancbrady
MicdoodleCore by Micdoodle8
Minechem by ljdp
Minecraft Comes Alive by WildBamaBoy
MineFactory Reloaded by skyboy026, powercrystals
MineTweaker by StanH
MineTweaker RecipeMaker by DoubleDoorDevelopment
ModTweaker by jaredlll08, joshie, SpitefulFox
Modular Powersuits by MachineMuse
MrCrayfish's Furniture Mod by Mr_Crayfish
Natura by mDiyo
NEI Addons by bdew
NEI Integration by Tonius
NetherOres by skyboy026, powercrystals
Not Enough Items by Chickenbones
NotEnoughCodecs by Mikeemoo
Nuclear Control by shedar
Numina by MachineMuse
OpenBlocks by Mikeemoo, boq
OpenComputers by Sangar
OpenModsLib by Mikeemoo, boq
OpenModularTurrets by Poenjabiesous, Keridos, UntouchedWagons
OpenPeripheral Core by Mikeemoo, boq
OpenPeripheral Integration by OpenMods Team
PneumaticCraft by MineMaarten
Power Converters 3 by covers1624
Practical Logistics by Ollie_Lansdell
Presence Footsteps by Hurricaaane
Project Red by MrTJP, Chickenbones
RadixCore by WildBamaBoy
Railcraft by CovertJaguar
Realistic Terrain Generation by WhichOnesPink 0.7.0
Redstone Arsenal by CoFH team
RFTools by McJty
Roguelike Dungeons by Greymerk
Simply Jetpacks by Tonius
SonarCore by Ollie_Lansdell
Soul Shards Reborn by Moze_Intel
Streams by delvr
Thaumcarpentry by zot201 - Granted
Thaumcraft by Azanor
Thaumic Energistics by Nividica
Thaumic Tinkerer by pixlepix, nekosune, Vazkii
ThaumicRevelations by Mortvana, MasterAbdoTGM50
Thermal Dynamics by TeamCoFH
Thermal Expansion by CoFH team
Thermal Foundation by CoFH team
Thermal Recycling by OreCruncher
TiC Tooltips by squeek502
Tinker's Construct by boni, mDiyo
Tinkers Steelworks by Toops, ephys
Traveller's Gear by Dawn_1006
TreeCapitator by bspkrs, DaftPVF
TubeStuff by immibis
vorbis-java-core by Maven - Granted
Voxel Menu Music by The Voxel Box - Granted
VoxelLib by The Voxel Box - Granted
VoxelMap by The Voxel Box - Granted
VoxelMenu by The Voxel Box - Granted
Waila by ProfMobius
Waila Harvestability by squeek502
WAILAPlugins by tterrag
Wireless Redstone CBE by Chickenbones
Witching Gadgets by BluSunrize

**Comment by NoireDvachevsky** [comment]
wow, looks like you are using much older versions than mine. Will look at it! Thanks!

**Comment by Sunconure11** [comment]
My modpack's permission list (will change again in the next update, I think I forgot a few things, and also I am adding a mod to change some of the things that can be obtained via fishing, all mods are kept up to date):

https://docs.google.com/spreadsheets/d/1j6upb7Bp7-NGyRfTOW8THsNbBc5hDbDKzKgeHevM-zw/edit?usp=sharing

**Comment by NoireDvachevsky** [comment]
Confirmed. RTG 0.7.0 is working well with Thermos. No cut-offs, no unpopulated chunks. Everything is fine. But only at 0.7.0 build. 0.8.0 and higher have bugs.

**Comment by Sunconure11** [comment]
https://github.com/Team-RTG/Realistic-Terrain-Generation/releases/tag/v0.8.0

Here is the list of all changes in 0.80. Maybe something here is relevant.

**Comment by enterprise12nx** [comment]
didnt know they had newer versions, if this gets fixed the updates look awesome so i would like to try it

**Comment by Sunconure11** [comment]
IIRC, they said there won't be new versions on 1.7.10 unless it is a critical issue.

**Comment by enterprise12nx** [comment]
So do we know if its a mod issue or thermos?
the new features of the mod look cool and i want to try them but not if we cant fix it xD and by we i mean Robotia :P

**Comment by Time6628** [comment]
This is a mod issue.

**Comment by enterprise12nx** [comment]
@whichonespink44

**Comment by whichonespink44** [comment]
Version 0.7.0 was the last version before we implemented the delayed decoration system, which is what allows RTG to have all those cool, new decorations combined with the improved terrains in 0.8.0+, so I'm assuming that's what is causing the compatibility issues with Thermos.

Without the delayed decoration system, RTG in its current form would be unplayable because of decoration 'rabbit-holing' whereby the decorations from one chunk bleed into another, causing it to start loading & decorate, which bleed into another chunk, causing it to start loading & decorate, which bleed into another chunk, causing it to start loading & decorate, etc etc, etc. Meanwhile, the first chunk that was trying to load just hangs there waiting for all the other chunks to finish loading & decorating before it can finish loading itself.

To get around this, the delayed decoration system basically stores all new chunks in a cache instead of loading them, and only loads them when its neighbours have finished decorating. And it's this caching system that seems to be incompatible with Thermos.

Unfortunately, the only way I see this issue getting resolved is if Thermos changes the way its chunk loading system works so that it's compatible with RTG's delayed decoration system, or if RTG changes its delayed decoration system to be compatible with Thermos. In both cases, I'm afraid the burden of responsibility would be in the hands of the Thermos team (or someone else from the modding community) because Team RTG just doesn't have the resources to dedicate to this at the moment, nor do we have the resources to be able to officially support other server platforms.

**Comment by Sunconure11** [comment]
@CyberdyneCC what do you say regarding this?

**Comment by Time6628** [comment]
I'm going to guess this has something to do with the way we fixed the "already decorating" crash.

**Comment by enterprise12nx** [comment]
@Time6628 @Robotia that seems possible..i barely know code but i remember reading about that in the update, however this isnt a MUST be fixed now, im aware everyone is busy but hopefully within a few months it could be fixed!

**Comment by Sunconure11** [comment]
Say, if Streams is indeed the culprit, could the fact that it is coded in Scala be a possible reason for this? Does thermos have any inherent incompatibilities with Scala-based mods?

**Comment by Robotia** [comment]
I don't think there is any incompatibility concerning Scala, I didn't have problems running mods written in it.

**Comment by Eufranio** [comment]
What about adding a config option that let RTG does what it want, without bukkit changing stuff?
