### ISSUE TITLE
Server unusual error

### ISSUE THREAD

**Issue by Arobcher** [CyberdyneCC/Thermos#502]
**Server Log:** *(https://gist.github.com/Arobcher/90a7d4d64fcbf72f82c02ea5381246fa)*

**FML Log(s):** *(https://gist.github.com/Arobcher/90a7d4d64fcbf72f82c02ea5381246fa)*

**Explanation of issue:*Server unusual error*

**How to recreate this issue:*I do not understand how he reproduced, the problem is probably block loading*

**Modpack Name:** http://www.filedropper.com/mods_15**(Only if public)*

**Mods Installed:**

**Plugins Installed:*
![c574ea0a-698e-11e6-9d82-39a59ceb9cc3](https://cloud.githubusercontent.com/assets/11995478/17916414/a6ecb6f6-69e5-11e6-8bb7-5a8f66a65efd.png)
*

**Warmroast Report:** *(Optional)*

**Thermos Version:*Thermos-1.7.10-1614-server-58*

**Forge Version:*1.7.10-Forge10.13.4.1614-1.7.10*

**Comment by iKaneki-Ken** [comment]
Problem isn't block loading, the problem is block access.

A plugin you have called RecipeManager is causing the stall when using the UUIDFetcher API when a player accesses a block. The block in question is a Furnace, it's trying to get the UUID of either the user that owns it, or is trying to set the owner of the furnace.

All in all, this is an external issue, it's not being caused by Thermos.

**Comment by Arobcher** [comment]
thanks 
I will go to delete this plugin
