### ISSUE TITLE
[Investigation] Figure out why block-lag happens

### ISSUE THREAD

**Issue by Robotia** [CyberdyneCC/Thermos#54]
When a server is lagging and a player breaks a block, sometimes it reverts back and is as though the player never broke the block. 
This should be easily fixable by creating some kind of queue of block breaks. I will look into why this happens and see what, if anything, can be done about it.

**Comment by TerdyTheTerd** [comment]
My understanding is the client renders the block as gone when the player "breaks" but then the server gets overloaded before it can send the packet data back to the client for it to be officially gone, so once the server catches up and sends that packet the client has to re-render it since according to the server is it still there. I'm not sure but maybe placing the queue so the client sends a request before it attempts to remove the block from rendering, that way the client wont get the ok to stop rendering the broken block until the server is actually ready and caught up.

This would be nicer to have to wait a second for a block to get removed rather than have to mine it 3 times before it gets removed.

**Comment by Robotia** [comment]
@TerdyTheTerd `This would be nicer to have to wait a second for a block to get removed rather than have to mine it 3 times before it gets removed.` My thoughts exactly!

**Comment by spannerman79** [comment]
I've seen this happen not when the server is overloaded but if there is a large amount of ping between server and client.

The server could be running at 20TPS, no spikes etc, the connecting client could be running perfectly. But if the ping is more then ~200ms (ish) or if there was a lag spike (either from server, path to client or even on client side due to "software emulating network hardware") this happens often.

The major cause of this that I have found comes down to GSP's.  Game Service Providers.  They overload their services expecting people not to use 100% of whats provided in order to make a profit.

The only real way to have a modded server - including kcauldron - is to ensure that your VPS node isn't overloaded, or have a dedicated server.

**Comment by iKaneki-Ken** [comment]
It's simply because the client renders it as gone when you break it, but when the server sends the synchronization packet, it corrects the client.

**Comment by Robotia** [comment]
Unlikely.
